spring:
  datasource:
    url: jdbc:mysql://localhost:3306/AssessmentDB
    password: root
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true